# Generated by Django 5.0.4 on 2024-05-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verproduction',
            name='description',
        ),
        migrations.AlterField(
            model_name='production',
            name='duration',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Contenido',
        ),
    ]
