# Generated by Django 5.0.4 on 2024-05-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_remove_verproduction_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verproduction',
            options={},
        ),
        migrations.RemoveField(
            model_name='verproduction',
            name='popularity',
        ),
    ]
