# Generated by Django 5.0.4 on 2024-05-17 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_verproduction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verproduction',
            name='id_production',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myApp.production'),
            preserve_default=False,
        ),
    ]
