# Generated by Django 5.0.4 on 2024-05-17 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_verproduction_id_production'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VerProduction',
        ),
    ]
