# Generated by Django 5.0.4 on 2024-05-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_perfiladministrador_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
